### ISSUE TITLE
FPX330-S101  or FPX330-H101 

### ISSUE THREAD

**Issue by MichielBbal** [jess-moss/koch-v1-1#11]
In your YouTube video (https://www.youtube.com/watch?v=8nQIg9BwwTk) I see you use the FPX330-S101. While in the 'sourcing parts' you mention FPX330-H101. Which one should we use? Thank you.

**Comment by jess-moss** [comment]
Per the BoM You will need FPX330-H101. You can either 3D print or buy FPX330-S101 as well (see footnote 12). Let me know if this is still not clear.

**Comment by MichielBbal** [comment]
Thanks. All clear, was lucky to have some old M2's laying around.
