### ISSUE TITLE
Leader arm base is different on video x github

### ISSUE THREAD

**Issue by diegoakel** [jess-moss/koch-v1-1#14]
This base:

![image](https://github.com/user-attachments/assets/48eb77ac-f767-44b3-8d7c-626561290288)

Is different from the one on the hardware/leader folder.

![image](https://github.com/user-attachments/assets/fecf5c06-dd91-42d7-a054-4a6cc264de7a)

**Comment by includingThis** [comment]
We had no issues assembling the parts nevertheless. However, in the video the servo is placed in a position turned 90 degrees. May be related to different base layout. Drawing in the manual confirms correct servo position parallel to the long side of the base.

**Comment by diegoakel** [comment]
Yes, not a real problem to be honest. Maybe just a version difference between video and repo. I guess this issue could be closed.
