### ISSUE TITLE
Plug 1 / plug 2 on the servos, does it matter?

### ISSUE THREAD

**Issue by includingThis** [jess-moss/koch-v1-1#18]
How to distinguish plug 1 from plug 2 on the hardware? Or is this irrelevant?
We don't want to break the dynamixels and are unsure whether we can put the cables in either of the two plugs of the servos? 

![grafik](https://github.com/user-attachments/assets/03c93eff-ba31-482c-8632-4709d0fe21f4)

**Comment by diegoakel** [comment]
this is irrelevant

**Comment by includingThis** [comment]
Great, thanks!

**Comment by includingThis** [comment]
closed
