### ISSUE TITLE
How should I assemble this in China?

### ISSUE THREAD

**Issue by Jerry-155** [jess-moss/koch-v1-1#7]
I would like to know where in China I can source these parts and assemble a robotic arm, or just buy a finished product that can be plugged into the lerobot.tanks

**Comment by CHANGgreenEVER** [comment]
Same problem

**Comment by Felix-Zhenghao** [comment]
Hi, I have bought all stuff from TaoBao and I will send a PR perhaps today or tomorrow.

**Comment by Hezhexi2002** [comment]
> Hi, I have bought all stuff from TaoBao and I will send a PR perhaps today or tomorrow.

Wonderful work!I'd like to build one arm following your sheet after I finish the exam!
